name: Precompiler
main: Precompiler\Precompiler
version: "v3"
author: 
- "hm"
- "organic"
api:
- "3.0.0"
- "3.1.0"
- "4.0.0"   

commands:
 생성:
  default: OP
 실행:
  default: OP
 올림:
  default: OP
 내림:
  default: OP
 추출:
  default: OP
 run:
  default: OP